name: Build-Test

on:
  push: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Node Init
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Node Packages
        run: npm ci
        
      - name: Build Local
        run: npm run build