name: Build-Test

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
          
      - name: Install Node Packages
        run: npm ci
        
      - name: Build Local
        run: npm run build

      - name: Run Markdown linting
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: docs/**/*.md
          config: .markdownlint.yaml
