name: Build-Test

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - uses: actions/checkout@v3
      -
        name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: 'yarn'
      -
        name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile
      -
        name: Build
        run: yarn run build
