name: Build-Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install

      - name: Install Node Packages
        run: yarn install --frozen-lockfile

      - name: Build Local
        run: yarn run build
